// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import NetworkErrorPage from "@/components/NetworkErrorPage";
import { SyncObserver } from "@/components/layout/SyncObserver";
// import { FontResizer } from "@/components/layout/FontResizer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SliceFlo",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Required for Impler widget */}
        <script
          type="text/javascript"
          src="https://embed.impler.io/embed.umd.min.js"
          async
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="brand"
          themes={["light", "dark", "brand", "dark-contrast", "light-contrast"]}
          enableSystem={false}
          disableTransitionOnChange
        >
          <AuthProvider>
            <SyncObserver />
            {/* <FontResizer /> */}
            <NetworkErrorPage />
            {children}
            {/* <Toaster position="top-right" richColors /> */}
            <Toaster />
          </AuthProvider>

        </ThemeProvider>
      </body>
    </html>
  );
}
