// utils/iconMap.ts
import {
    House,
    Envelope,
    Star,
    Users,
    FileText,
    TrendUp,
    PushPinSimpleSlash,
    PushPinSimple,
    CaretDown,
    PushPin,
    List,
    Tag,
    CheckSquare,
    Trash,
    Export,
    Archive,
    Alarm,
    ArrowsInSimple,
    UserCircle,
    Rows,
    TextAa,
    Function,
    UsersThree,
} from "phosphor-react";

import {
    Focus,
    PanelsTopLeft,
    Trash2,
    User as LucideUser,
    Airplay,
    Settings,
    Search,
    Target,
    Clipboard,
    Watch,
    ChevronsLeft,
    ChevronsRight,
    ArrowDownUp,
    Filter,
    PaintBucket,
    EyeOff,
    ArrowDownAZ,
    ArrowUpZA,
    ArrowDown01,
    ArrowUp01,
    MoveUp,
    MoveDown,
    ChartNoAxesCombined,
    FileText as LucideFileText,
    Paperclip,
    GripVertical,
    TrendingUp,
    Move,
    Copy,
    ShoppingBag,
    CalendarCheck,
    X,
    Bold,
    Italic,
    Underline,
    Strikethrough,
    AlignLeft,
    AlignJustify,
    AlignRight,
    ChevronsUp,
    ChevronDown,
    ChevronRight,
    ChevronUp,
    ArrowLeft,
    Users2,
    Trophy,
    Share2,
    Plus,
    Ellipsis,
    Palette,
    Edit3,
    Dices,
    DollarSign,
    GitBranch,
    Milestone,
    ChevronDown as DropdownIcon,
    Type as TextIcon,
    Calendar as DateIcon,
    AlignLeft as TextareaIcon,
    Hash as NumberIcon,
    Percent as PercentageIcon,
    Globe as WebsiteIcon,
    CheckSquare as CheckboxIcon,
    BarChart3 as ProgressAutoIcon,
    BarChart2 as ProgressManualIcon,
    Star as RatingIcon,
    Calculator as RollupIcon,
    GitBranch as RelationshipIcon,
    Users as PeopleIcon,
    Mail as EmailIcon,
    Phone as PhoneIcon,
    ListTodo as TasksIcon,
    FileText as FilesIcon,
    Calculator as FormulaIcon,
    ThumbsUp as VotingIcon,
    Timer as TimeTrackingIcon,
    Copy as MirrorIcon,
    Link as DependencyIcon,
    Hash as AutoNumberIcon,
    Link as TaskIdIcon,
    Wifi as IpAddressIcon,
    Share as SocialMediaIcon,
    User,
    Layers,
    Link2,
    Activity,
    History,
    CloudDownload,
    CloudUpload,
    EllipsisVertical,
    Eye,
    CheckCheck,
    LogOut,
    Clock4,
    Repeat,
    Bell,
    // Additional Lucide React replacements for Material UI icons
    BookOpen as ReadMoreIcon,
    FolderOpen as CategoryIcon,
    BarChart3 as EqualizerIcon,
    Pin as PinIcon,
    ThumbsDown as ThumbsUpDownIcon,
    FileText as DescriptionIcon,
    MoreHorizontal as MoreHorizIcon,
    Paperclip as AttachFileIcon,
    Ban as BlockIcon,
    Users as GroupsIcon,
    PlayCircle as PlayCircleIcon,
    Flag as FlagIcon,
    Calendar as TodayIcon,
    CalendarDays as EventIcon,
    ArrowUpDown as ImportExportIcon,
    CheckCircle as CheckCircleIcon,
    CheckSquare2 as CheckBoxIcon,
    Type as FormatSizeIcon,
    MapPin as LocationIcon,
    Monitor as MonitorIcon,
    Calendar as CalendarIcon,
} from "lucide-react";

import GoalIcon from "@/public/icons/goals";
import DocsIcon from "@/public/icons/docs";
import WhiteboardIcon from "@/public/icons/whiteboard";
import TimesheetIcon from "@/public/icons/timesheet";
import ConvertIcon from "@/public/icons/Convert";

const iconMap: Record<string, React.ComponentType<{ size: number; className?: string; color?: string }>> = {
    house: House,
    sort: ArrowDownUp,
    filter: Filter,
    pinColumns: PushPin,
    members: Users,
    adaptiveColor: PaintBucket,
    clearFilters: EyeOff,
    envelope: Envelope,
    star: Star,
    users: Users,
    fileText: FileText,
    trendUp: TrendUp,
    focus: Focus,
    panelsTopLeft: PanelsTopLeft,
    goals: GoalIcon,
    docs: DocsIcon,
    whiteboard: WhiteboardIcon,
    timesheet: TimesheetIcon,
    readMore: ReadMoreIcon,
    category: CategoryIcon,
    pin: PushPinSimple,
    unpin: PushPinSimpleSlash,
    trash: Trash2,
    user2: LucideUser,
    airplay: Airplay,
    settings: Settings,
    search: Search,
    target: Target,
    clipboard: Clipboard,
    watch: Watch,
    caretDown: CaretDown,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    sortAZ: ArrowDownAZ,
    sortZA: ArrowUpZA,
    sortNum01: ArrowDown01,
    sortNum10: ArrowUp01,
    list: List,
    labels: Tag,
    checkbox: CheckSquare,
    status: ChartNoAxesCombined,
    priority: LucideFileText,
    files: Paperclip,
    timeline: EqualizerIcon,
    numbers: PinIcon,
    // voting: ThumbsUpDownIcon,
    dotsvertical: GripVertical,
    trendingUp: TrendingUp,
    delete: Trash,
    moveTo: Move,
    duplicate: Copy,
    export: Export,
    archive: Archive,
    app: ShoppingBag,
    convert: ConvertIcon,
    docView: DescriptionIcon,
    clock: Alarm,
    dateIcon: CalendarCheck,
    close: X,
    moreHorizontal: MoreHorizIcon,
    attachFile: AttachFileIcon,
    block: BlockIcon,
    membersGroup: GroupsIcon,
    flag: FlagIcon,
    collapse: ArrowsInSimple,
    user: UserCircle,
    playCircle: PlayCircleIcon,
    twoRows: Rows,
    textStrike: Strikethrough,
    upperCase: TextAa,
    bold: Bold,
    italic: Italic,
    underline: Underline,
    alignLeft: AlignLeft,
    alignCenter: AlignJustify,
    alignRight: AlignRight,
    startDate: TodayIcon,
    endDate: EventIcon,
    twoDownArrow: ChevronsUp,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    arrowLeft: ArrowLeft,
    users2: Users2,
    trophy: Trophy,
    phosphorUser: User,
    phosphorUsers: Users,
    phosphorUsersThree: UsersThree,
    share2: Share2,
    plus: Plus,
    ellipsis: Ellipsis,
    palette: Palette,
    edit3: Edit3,
    dices: Dices,
    dollarSign: DollarSign,
    gitBranch: GitBranch,
    milestone: Milestone,
    targetIcon: Target,
    // Field type icons
    dropdownIcon: DropdownIcon,
    textIcon: TextIcon,
    dateIcon2: DateIcon,
    textareaIcon: TextareaIcon,
    numberIcon: NumberIcon,
    percentageIcon: PercentageIcon,
    websiteIcon: WebsiteIcon,
    checkboxIcon: CheckboxIcon,
    progressAutoIcon: ProgressAutoIcon,
    progressManualIcon: ProgressManualIcon,
    ratingIcon: RatingIcon,
    rollupIcon: RollupIcon,
    relationshipIcon: RelationshipIcon,
    peopleIcon: PeopleIcon,
    emailIcon: EmailIcon,
    phoneIcon: PhoneIcon,
    tasksIcon: TasksIcon,
    filesIcon: FilesIcon,
    formulaIcon: FormulaIcon,
    votingIcon: VotingIcon,
    timeTrackingIcon: TimeTrackingIcon,
    mirrorIcon: MirrorIcon,
    dependencyIcon: DependencyIcon,
    autoNumberIcon: AutoNumberIcon,
    taskIdIcon: TaskIdIcon,
    ipAddressIcon: IpAddressIcon,
    socialMediaIcon: SocialMediaIcon,
    importExport: ImportExportIcon,
    radioCheckedIcon: CheckCircleIcon,
    checkboxIcon2: CheckBoxIcon,
    textAreaIcon: FormatSizeIcon,
    functionIcon: Function,
    locationIcon: LocationIcon,
    monitorIcon: MonitorIcon,
    arrowUp: MoveUp,
    arrowDown: MoveDown,
    layers: Layers,
    moreVert: EllipsisVertical,
    link: Link2,
    activity: Activity,
    history: History,
    cloudDownload: CloudDownload,
    cloudUpload: CloudUpload,
    eye: Eye,
    checkCheck: CheckCheck,
    exit: LogOut,
    time: Clock4,
    repeat: Repeat,
    notification: Bell,
};

export default iconMap;
